export const transactions = [
    {
        id: 1,
        name: "Loan Disbursement - Appliances",
        type: "incoming",
        date: "2023-06-15",
        amount: 4000000,
        status: "completed",
        loanType: "appliances",
    },
    {
        id: 2,
        name: "Monthly Repayment",
        type: "outgoing",
        date: "2023-06-05",
        amount: 125000,
        status: "completed",
        loanType: "regular",
    },
    {
        id: 3,
        name: "Loan Application Fee",
        type: "outgoing",
        date: "2023-05-28",
        amount: 5000,
        status: "completed",
        loanType: "commodity",
    },
    {
        id: 4,
        name: "Loan Disbursement - Regular",
        type: "incoming",
        date: "2023-05-20",
        amount: 2500000,
        status: "completed",
        loanType: "regular",
    },
    {
        id: 5,
        name: "Late Payment Penalty",
        type: "outgoing",
        date: "2023-05-15",
        amount: 7500,
        status: "completed",
        loanType: "regular",
    },
];


export const loanPayments = [
    {
        id: "LP-1001",
        name: "Monthly Installment - Regular Loan",
        type: "repayment",
        date: "2023-06-10",
        amount: 125000,
        status: "completed",
        loanId: "LN-2023-001",
        loanType: "regular",
        paymentMethod: "bank transfer",
        reference: "PMT-789012",
    },
    {
        id: "LP-1002",
        name: "Final Balloon Payment - Appliances Loan",
        type: "full settlement",
        date: "2023-06-05",
        amount: 850000,
        status: "completed",
        loanId: "LN-2023-002",
        loanType: "appliances",
        paymentMethod: "mobile money",
        reference: "PMT-789013",
    },
    {
        id: "LP-1003",
        name: "Late Payment - Regular Loan",
        type: "penalty",
        date: "2023-05-28",
        amount: 15000,
        status: "completed",
        loanId: "LN-2023-001",
        loanType: "regular",
        paymentMethod: "cash",
        reference: "PMT-789014",
    },
    {
        id: "LP-1004",
        name: "Early Repayment - Commodity Loan",
        type: "partial prepayment",
        date: "2023-05-20",
        amount: 300000,
        status: "processing",
        loanId: "LN-2023-003",
        loanType: "commodity",
        paymentMethod: "bank transfer",
        reference: "PMT-789015",
    },
    {
        id: "LP-1005",
        name: "Scheduled Payment - Regular Loan",
        type: "repayment",
        date: "2023-05-15",
        amount: 125000,
        status: "failed",
        loanId: "LN-2023-001",
        loanType: "regular",
        paymentMethod: "card",
        reference: "PMT-789016",
        failureReason: "Insufficient funds",
    }
];
